"""sort_json5.py

As an experiment, and because it's not fun to do this sort of thing manually,
everything below this paragraph was originally generated by Claude Opus 4.6,
which I asked to figure out how to sort the keys automatically. I made some
edits to the generated code, but I am forced to admit that it saved me from
having to do a boring task myself.

----

Sort top-level keys in a JSON5 file alphabetically (case-insensitive),
preserving comments and formatting by operating on raw text lines.

Each top-level entry block consists of:
  - The key line:  '    "KeyName": ['
  - Array content lines (values, comments, blanks)
  - The closing line: '    ],'

Comment/blank lines between entries are attached as trailing lines of the
preceding entry, so they move together during sorting.
"""
from __future__ import annotations

import re
import sys


KEY_LINE_RE = re.compile(r'^    "(.+)": \[\s*$')


def parse_blocks(lines):
    """Parse the body lines (between { and }) into entry blocks.

    Returns a list of (key, block_lines) tuples. The key is the top-level
    dictionary key extracted from the entry's opening line; block_lines is
    the list of raw text lines for that entry (including any trailing
    comment/blank lines that follow its closing '],' before the next key).
    """
    blocks = []
    current_key = None
    current_lines = []

    for line in lines:
        m = KEY_LINE_RE.match(line)
        if m:
            # Starting a new entry — flush the previous one
            if current_key is not None:
                blocks.append((current_key, current_lines))
            current_key = m.group(1)
            current_lines = [line]
        else:
            current_lines.append(line)

    # Flush the last entry
    if current_key is not None:
        blocks.append((current_key, current_lines))

    blocks.sort(key=lambda b: b[0].casefold())
    return (block[1] for block in blocks)


def sort_json5_file(path):
    with open(path) as f:
        all_lines = f.readlines()

    # First line is '{', last line is '}'
    header = all_lines[0]   # '{\n'
    footer = all_lines[-1]  # '}\n'
    body = all_lines[1:-1]

    blocks = parse_blocks(body)

    # Strip trailing blank/comment lines from the very last block (they
    # belong before '}', not after a specific entry — but in practice the
    # last block shouldn't have trailing lines beyond its '],').

    with open(path, 'w', newline='\n') as f:
        f.write(header)
        for block in blocks:
            for line in block:
                f.write(line)
        f.write(footer)


if __name__ == '__main__':
    sort_json5_file(sys.argv[1])
    print("Sorted JSON5 keys! ✅")
