"""sort_check.py

As an experiment, and because it's not fun to do this sort of thing manually,
everything below this paragraph was originally generated by Claude Opus 4.6,
which I asked to figure out how to sort the keys automatically. I made some
edits to the generated code, but I am forced to admit that it saved me from
having to do a boring task myself.

----

Verify that top-level keys in a JSON5 file are sorted alphabetically
(case-insensitive). Exits non-zero if keys are out of order.
"""
from __future__ import annotations

import sys

import json5


def capture_keys(pairs):
    keys.extend(k for k, _ in pairs)
    return dict(pairs)


keys = []

with open(sys.argv[1]) as f:
    json5.load(f, object_pairs_hook=capture_keys)

sorted_keys = sorted(keys, key=str.casefold)

if keys == sorted_keys:
    print("Top-level keys are sorted! ✅")
    sys.exit(0)
else:
    for i, (actual, expected) in enumerate(zip(keys, sorted_keys)):
        if actual != expected:
            print(
                f'Keys not sorted: "{actual}" is out of order ❌'
            )
            print(
                "(Hint: Run `make sort` to automatically sort the keys.)"
            )
            break
    sys.exit(1)
